---
title: "Gender Pay Gap Across Different Racial and Ethnic Groups"
author: "Luz RC"
date: "2025-06-08"
categories: [goals,general]
---

# Introduction

The gender pay gap is a global issue, with women consistently earning less than men. Despite significant progress made by many countries, this continues to be a persistent problem. In this project, we will examine how the United States has addressed the gender pay gap over the period from 1988 to 2023. Additionally, we will explore how the pay gap varies across different racial and ethnic groups. This will help us answer the question: Do men consistently earn more than women within each racial/ethnic group, or are there any exceptions?

## Prediction

Based on personal knowledge, I assume that men earn more than women across all racial and ethnic groups, regardless of background.

## Data Source

The data used in this project was obtained from a dataset on [Kaggle](https://www.kaggle.com/datasets), originally sourced from the U.S. Department of Labor.

# Approach

The data set provides information on median annual salaries in the United States, broken down by race and sex, from 1988 to 2023. According to the data set owner on Kaggle, the data was downloaded from the official website of the U.S. Department of Labor. Early years that did not include salary data for certain ethnic groups were removed. The data set was then reorganized to improve accessibility and analytical usability.

The variables in the data set include:

-   **Year**

-   **Salary**

-   **Sex** (Male and Female)

-   **Race/Ethnicity** (Asian, White, Black, and Hispanic)\

# Tools

The tools used for this project include:

-   **R** and **RStudio** on Posit Cloud

-   **GitHub** for website hosting

-   The **tidyverse** package for data analysis and visualization\

# Approach/Predictions

To answer the question of whether men consistently earn more than women within each racial/ethnic group, and to identify any exceptions, we will create a series of visualizations. These graphs will help us compare salaries within each racial/ethnic and gender group and reveal how gender and race/ethnicity correlate with income levels. Additionally, we will produce a graph comparing the earnings of white women to those of non-white men.

Based on this analysis, my prediction is that white men will earn more than individuals in any other racial/ethnic or gender group.

# Results

## Code

```{r}
#| paged-print: false
library(tidyverse)
salarydata <- read.csv("../../salary_bras.csv")

#To clean and transform the data for better use

salarydata <- gather(
  salarydata,
  group,
  salary,
  Asian.Men:White.Women,
  factor_key = TRUE
)


salarydata$ethnicity <- str_split_i(
  salarydata$group,
  "\\.",
  1
)

salarydata$gender <- str_split_i(
  salarydata$group,
  "\\.",
  2
)

#To filter a data set without the total values

salary_data_filter <- salarydata |> filter(ethnicity != "Total")

#To create a graph that shows how are women and man pay across racial groups

 ggplot(salary_data_filter, mapping = aes (x = Year, y = salary, group = gender,
                                   color = gender)) +
   geom_line()+
   geom_point()+
   facet_wrap(~ethnicity) +
   labs(title = "Gender Pay Gap by Racial/Ethnic Groups in the U.S. 1988 - 2023",
        y = "Salary",
        x = "Year", color = "Gender")+
   theme_minimal()
 
 #This graph compares earnings between men and women across all racial and ethnic groups, showing that men consistently earn more than women, with Asian men earning the highest overall.


#To create a filter of Women only

salarydata_women <- salary_data_filter |> filter(gender == "Women")

#To create a filter of Men only

salarydata_men <- salary_data_filter |> filter(gender == "Men")

#To create a graph for women pay gap across groups 

ggplot(salarydata_women, aes(
  x = Year, y = salary, color = ethnicity))+
  geom_line()+
  geom_point()+
  labs(title ="Race/Ethnicity Pay Gap Within Women", x = "Year", y = "Salary",
       color = "Race/Ethnicity")+
  theme_linedraw()

#This graph displays the median earnings of women across different racial and ethnic groups, highlighting that Asian women consistently earn more than women in other groups

#To make a graph to show the pay gap within men 

ggplot(salarydata_men, aes(
  x = Year, y = salary, color = ethnicity))+
  geom_line()+
  geom_point()+
  labs(title ="Race/Ethnicity Pay Gap Within Men", x = "Year", y = "Salary",
       color = "Race/Ethnicity")+
  theme_linedraw()

#This graph shows the median earnings of men across various racial and ethnic groups, with Asian men earning the highest compared to men from other groups.

# To create a filter of Non White Males vs White women 

salarydata_whitewomen <- salary_data_filter |> filter((
  gender == "Men" & ethnicity != "White") | (
    gender == "Women" & ethnicity == "White"))

# The creation of the plot of the comparison

ggplot(salarydata_whitewomen, aes(
  x=Year, y=salary, color = interaction(gender, ethnicity)))+
  geom_line()+
  geom_point()+
  labs(title = "Salary Comparison: Men (Non-White) vs White Women", x = "Year",
       y = "Salary", color = "Gender & Race/Ethnicity")+
  theme_linedraw()

#This graph shows that over the past decade, White women’s median salary has risen above that of Black and Hispanic men, though a significant gap remains between them and Asian men.


# To create a filter of Men vs Asian women 

salarydata_asianwomen <- salary_data_filter |> filter((
  gender == "Men") | (
    gender == "Women" & ethnicity == "Asian"))

# The creation of the plot of the comparison

ggplot(salarydata_asianwomen, aes(
  x=Year, y=salary, color = interaction(gender, ethnicity)))+
  geom_line()+
  geom_point()+
  labs(title = "Salary Comparison: Men vs Asian Women", x = "Year",
       y = "Salary", color = "Gender & Race/Ethnicity")+
  theme_linedraw() 

#I created this graph to explore the surprising trend observed in the first graph. This graph was created to examine the trend observed in the initial analysis, showing that since 2020, the median salary of Asian women has surpassed that of White men, while Asian men have consistently maintained the highest earnings overall.
  
```

# Discussion

The data confirm that men generally earn more than women across all racial and ethnic groups. Surprisingly, Asian men and women both earn more than White men, challenging the common belief that White men have the highest earnings.
